---
title: "Thomas Lieb's CV"
author: Thomas Lieb
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: false
  version: '1.0' # format: x.y
output:
  pagedown::html_resume:
    # note: order here matters, the latter overrides the former
    css: ['resume.css', 'dd_cv.css']
    self_contained: true
    keep_md: yes
---

```{=html}
<!--
Tailoring CV for specific applications

* copy & adjust spreadsheet and run script by adjusting spreadsheet link
* if code needs to be adjusted, could be done via a branch or copy of code saved along with CV
-->
```

```{r cv_data_url, include = FALSE}
cv_data_url <- "https://docs.google.com/spreadsheets/d/1KcTSyanKHQ1jGnwVd6AxMcb3zXLvt-2RKzsPOfmI5Cw/edit#gid=917338460"

# use url from local .Renviron file instead, if present
if (nchar(Sys.getenv("CV_DATA_URL")) > 0) {
  cv_data_url <- Sys.getenv("CV_DATA_URL")
  print(1)
}
```


```{r read_data, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(conflicted)
library(magrittr) # For the pipe
require(here)

here::i_am("cv.rmd")

source(here::here("cv_printing_functions.r"))

# Read in all data and initialize a CV printer object
offline <- F
if (!offline) {
  CV <- create_CV_object(
    data_location = cv_data_url,  
    pdf_mode = params$pdf_mode,
    sheet_is_publicly_readable = FALSE
  )
  saveRDS(CV, "CV.RDS")
} else {
  CV <- readRDS("CV.RDS")
}
CV$pdf_mode <- params$pdf_mode

# read in CSS file to extract colors from
require(cssparser)
css_root <- cssparser::read_css("dd_cv.css")$`:root`
```

```{r parse_versions}
v_md <- params$version
v_data <- CV$settings$data_version
v_txt <- glue::glue("v{v_md}/{v_data}")
```


```{r parse_mode}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r generate_qr_code, include=FALSE}
if (FALSE) {
  require(qrcode)
  link <- "https://www.linkedin.com/in/thomas-lieb-158576a0/"
  qr <- qr_code(link)
  generate_svg(
    qr, "frame.svg", background = css_root$`--sidebar-background-color`
    )
}
```


<!-- image at the top of aside -->
```{r insert_image}
CV %>% print_image_html()
```

```{r link_online_version}
mode <- ifelse(params$pdf_mode, "pdf", "html")
CV %>% print_online_version_text(mode)
```

<!--
Contact {#contact}
--------------------------------------------------------------------------------
-->
```{r}
CV %<>% print_text("header_contact", "plain",'  {#contact}')
cat("\n--------------------------------------------------------------------------------\n")
CV %>% print_contact_info()
```

<!--
Advanced Tech Skills {#main_tech_skills}
--------------------------------------------------------------------------------
-->
```{r advanced_tech_skills}
CV %<>% print_text("header_adv_tech_skills", "plain",'  {#main_tech_skills}')
cat("\n--------------------------------------------------------------------------------\n")
CV %>% print_skill_bars(
  bar_color = css_root$`--main-color-headers`, 
  bar_background = css_root$`--main-color-skillbar-background`)
```


<!--
Other Tech Skills {#other_tech_skills}
--------------------------------------------------------------------------------
-->
```{r other_tech_skills}
CV %<>% print_text("header_other_tech_skills", "plain",'  {#other_tech_skills}')
cat("\n--------------------------------------------------------------------------------\n")
CV %>% print_skills_text(category_filter = "other_tech", glue_template = "list", collapse = "\n")
```

<!--
Management Skills {#management_skills}
--------------------------------------------------------------------------------
-->

```{r mgmt_skills}
CV %<>% print_text("header_mgmt_skills", "plain",'  {#management_skills}')
cat("\n--------------------------------------------------------------------------------\n")
CV %>% print_skills_text(category_filter = "management", glue_template = "list", collapse = "\n")
```

<!--
Attributes {#attributes}
--------------------------------------------------------------------------------

```{r}
CV %>% print_skills_text(category_filter = "attributes")
```
-->

<!--
Languages {#languages}
--------------------------------------------------------------------------------
-->
```{r languages}
CV %<>% print_text("header_languages", "plain",'  {#languages}')
cat("\n--------------------------------------------------------------------------------\n")
CV %>% print_languages_table()
```


Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with the R package [pagedown](https://github.com/rstudio/pagedown){target="_blank"}.
<br>Source code available on [Github](https://github.com/rietho/cv){target="_blank"}.
```{r last_updated_date_and_version}
cat('<br>')
if (!CV$settings$show_last_updated_date) {
  cat(glue::glue("Last updated on {Sys.Date()} | "))
}
cat(v_txt)
```

# Main

```{r header_name}
CV %<>% print_text("header_name", "title", " {#title}")
```

```{r sub_header}
CV %<>% print_text("subheader", "plain")
```


```{r subtitle}
CV %<>% print_text("subtitle", "subtitle")
```

```{r intro}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text("intro", "plain") 
```

<!--
## Work Experience {data-icon="suitcase"}
-->

```{r work_experience_header}
CV %<>% print_text("header_work_experience", "title", ' {data-icon="suitcase"}')
```


<!--
```{=html}
::: aside
```{r}
CV %<>% print_text('industy_experience_aside', "plain")
```
:::
```
-->

```{r}
CV %<>% print_section('industry_positions')
```

<!--
## Education {data-icon="graduation-cap" data-concise="true"}
-->

```{r education_header}
CV %<>% print_text("header_education", "title", ' {data-icon="graduation-cap" data-concise="true"}')
```

<!--
```{=html}
::: aside
```{r}
CV %<>% print_text('education_aside', "plain")
```
:::
```
-->

```{r}
glue_template <- "
### {title}

{institution}

{loc}

{timeline}

:::concise
{description_bullets}
:::
\n\n\n"
CV %<>% print_section('education', glue_template = glue_template)
```

```{=html}
<!-- These breaks just force a new page so section doesnt get cut off 
<br>
<br>
<br>
-->
```
